### ISSUE TITLE
Passage en version 4.0.0 - Zend vs Laminas (mail)

### ISSUE THREAD

**Issue by ytennevin** [EsupPortail/esup-sygal#17]
J'ai passé l'application en version 4.0.0
Il y a un oubli mineur de documentation dans 
doc/release-notes/v4.0.0.md 

Dans config/autoload/secret.local.php
il faut changer 
use Zend\Mail\Transport\Smtp;
par 
use Laminas\Mail\Transport\Smtp;

(le fichier dist contient bien le changement)

sinon cela déclenche une erreur. (cf. plus bas)

Note: on a aussi l'ajout d'un
namespace Application;
vers le début du fichier qui n'est pas documenté a priori ? le faut il vraiment ?

```
> mkdir -p public/unicaen && cp -r vendor/unicaen/app/public/unicaen public/
> mkdir -p public/unicaen && cp -r vendor/unicaen/db-import/public/unicaen public/
> mkdir -p vendor/mpdf/mpdf/ttfontdata && chmod -R 777 vendor/mpdf/mpdf/ttfontdata
> mkdir -p data/cache && chmod -R 777 data/cache && rm -rf data/cache/*
> mkdir -p data/DoctrineModule/cache && chmod -R 777 data/DoctrineModule/cache && rm -rf data/DoctrineModule/cache/*
> mkdir -p data/DoctrineORMModule/Proxy && chmod -R 777 data/DoctrineORMModule/Proxy && rm -rf data/DoctrineORMModule/Proxy/*
> vendor/bin/doctrine-module orm:clear-cache:query
PHP Fatal error:  Uncaught Assert\InvalidArgumentException: Value "Zend\Mail\Transport\Smtp" is not an element of the valid values: Laminas\Mail\Transport\Smtp, Laminas\Mail\Transport\Sendmail in /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php:288
Stack trace:
#0 /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php(969): Assert\Assertion::createException()
#1 /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php(989): Assert\Assertion::choice()
#2 /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php(61): Assert\Assertion::inArray()
#3 /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php(35): UnicaenApp\Service\Mailer\MailerServiceFactory->createTransport()
#4 /data/app-pg/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): UnicaenApp\Service\Mailer\MailerServiceFactory->__invoke()
#5 /data/app-pg/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#6 /da in /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php on line 63

Fatal error: Uncaught Assert\InvalidArgumentException: Value "Zend\Mail\Transport\Smtp" is not an element of the valid values: Laminas\Mail\Transport\Smtp, Laminas\Mail\Transport\Sendmail in /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php:288
Stack trace:
#0 /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php(969): Assert\Assertion::createException()
#1 /data/app-pg/vendor/beberlei/assert/lib/Assert/Assertion.php(989): Assert\Assertion::choice()
#2 /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php(61): Assert\Assertion::inArray()
#3 /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php(35): UnicaenApp\Service\Mailer\MailerServiceFactory->createTransport()
#4 /data/app-pg/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): UnicaenApp\Service\Mailer\MailerServiceFactory->__invoke()
#5 /data/app-pg/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#6 /da in /data/app-pg/vendor/unicaen/app/src/UnicaenApp/Service/Mailer/MailerServiceFactory.php on line 63
Script vendor/bin/doctrine-module orm:clear-cache:query handling the post-install-cmd event returned with error code 255

```

**Comment by ytennevin** [comment]
Autre soucis: j'ai des 

`Notice: Undefined variable: description in /data/app-pg/module/Application/view/application/these/partial/titre.phtml on line 34
`
qui s'affiche après la mise à jour à divers moments dans l'application (annuaire des thèses / affichage d'une thèse)
